In [4]:
import numpy as np

In [12]:
x = np.array([[1],[2],[3]])


In [13]:
x.shape

(3, 1)

In [14]:
print(f"A 3-D vector: \n {x}")

A 3-D vector: 
 [[1]
 [2]
 [3]]


In [18]:
y = np.array([[1],[2],[4]])

In [19]:
y.shape

(3, 1)

In [20]:
x+y

array([[2],
       [4],
       [7]])

In [21]:
np.add(y,x)

array([[2],
       [4],
       [7]])

Multiplication

In [24]:
np.multiply(x,y)

array([[ 1],
       [ 4],
       [12]])

In [25]:
x * y

array([[ 1],
       [ 4],
       [12]])