In [70]:
import numpy as np

In [71]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


transpose of matrix

In [72]:
print(arr1.T)
print(arr2.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


identy matrix

In [73]:
i_mat = np.identity(3,dtype = "int32")
i_mat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [74]:
arr1 + i_mat
arr2 + i_mat

array([[ 2,  2,  3],
       [ 4,  6,  6],
       [ 7,  8, 10]])

reversing

In [75]:
arr1 = np.flip(arr1)
print(arr1)
arr2 = np.flip(arr2)
print(arr2)




[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


slicing and indexing

In [76]:

arr2[1:3,1:3] = 1
print(arr2)

[[9 8 7]
 [6 1 1]
 [3 1 1]]
